//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbFirst
{
    using System;
    
    public enum ProductCategory : int
    {
        groceries = 1,
        sportgoods = 2,
        kitchengoods = 3,
        goodsforanimals = 4,
        goodsforbabies = 5,
        others = 6
    }
}
